export const apiErrorCodes = [
  'COMMON_VALIDATION_FAILED',
  'COMMON_BAD_REQUEST',
  'COMMON_UNAUTHORIZED',
  'COMMON_FORBIDDEN',
  'COMMON_NOT_FOUND',
  'COMMON_CONFLICT',
  'COMMON_PRECONDITION_REQUIRED',
  'COMMON_RATE_LIMITED',
  'COMMON_INTERNAL_ERROR',
  'COMMON_UPSTREAM_ERROR',
  'COMMON_SERVICE_UNAVAILABLE',
  'VALIDATION_REQUIRED',
  'VALIDATION_INVALID',
  'VALIDATION_INVALID_FORMAT',
  'VALIDATION_OUT_OF_RANGE',
  'VALIDATION_SIZE',
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_ACCOUNT_LOCKED',
  'AUTH_PASSWORD_CONFIRMATION_INVALID',
  'AUTH_USERNAME_ALREADY_REGISTERED',
  'AUTH_EMAIL_ALREADY_REGISTERED',
  'AUTH_REFRESH_TOKEN_INVALID',
  'AUTH_ACCOUNT_INACTIVE',
  'AUTH_LINKED_USER_NOT_FOUND',
  'AUTH_GOOGLE_REGISTRATION_REQUIRED',
  'AUTH_GOOGLE_ACCOUNT_ALREADY_EXISTS',
  'AUTH_GOOGLE_LINK_REQUIRED',
  'AUTH_GOOGLE_ALREADY_LINKED',
  'AUTH_GOOGLE_LINKED_TO_ANOTHER_USER',
  'AUTH_GOOGLE_LINKING_UNAVAILABLE',
  'AUTH_GOOGLE_NOT_CONFIGURED',
  'AUTH_GOOGLE_TOKEN_EXCHANGE_FAILED',
  'AUTH_GOOGLE_ID_TOKEN_INVALID',
  'AUTH_GOOGLE_OAUTH_CANCELLED',
  'AUTH_GOOGLE_OAUTH_STATE_INVALID',
  'AUTH_GOOGLE_OAUTH_REQUEST_INVALID',
  'AUTH_EMAIL_REQUIRED',
  'AUTH_EMAIL_VERIFICATION_INVALID',
  'AUTH_BOT_CHALLENGE_INVALID',
  'AUTH_BOT_CHALLENGE_UNAVAILABLE',
  'AUTH_EMAIL_VERIFICATION_RATE_LIMITED',
  'AUTH_VERIFICATION_EMAIL_DELIVERY_FAILED',
  'ACCOUNT_PASSWORD_CHANGE_UNAVAILABLE',
  'ACCOUNT_CURRENT_PASSWORD_INVALID',
  'ACCOUNT_PASSWORD_CONFIRMATION_INVALID',
  'ACCOUNT_RECOVERY_INVALID',
  'ACCOUNT_INACTIVE',
  'ACCOUNT_CHALLENGE_RATE_LIMITED',
  'ACCOUNT_CHALLENGE_INVALID',
  'PRIVACY_CONSENT_INVALID',
  'PRIVACY_REGISTRATION_INTENT_INVALID',
  'PRIVACY_GOOGLE_REGISTRATION_INVALID',
  'PRIVACY_CONSENT_REQUIRED',
  'MEMBERSHIP_PREMIUM_REQUIRED',
  'BOOK_ALREADY_EXISTS',
  'SESSION_LAST_WINDOW_REQUIRED',
  'SESSION_ANSWERED_QUESTION_DELETE_CONFLICT',
  'SESSION_QUESTION_ANSWER_ROUTE_REQUIRED',
  'SESSION_QUESTION_ANSWER_TYPE_INVALID',
  'STREAM_MESSAGE_FAILED',
] as const;

export type ApiErrorCode = (typeof apiErrorCodes)[number];

export interface ApiFieldError {
  field: string;
  code: ApiErrorCode | string;
}

export interface ApiError {
  code: ApiErrorCode | string;
  message?: string;
  fields: ApiFieldError[];
  requestId: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data: T | null;
  error: ApiError | null;
}
