CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(80) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NULL,
  auth_provider VARCHAR(40) NOT NULL DEFAULT 'local',
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_username (username),
  KEY idx_users_test_data (is_test_data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS books (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NULL,
  author VARCHAR(255) NULL,
  publisher VARCHAR(255) NULL,
  published_year INT NULL,
  isbn VARCHAR(32) NULL,
  language_code VARCHAR(16) NULL,
  description TEXT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'ai',
  source_ref VARCHAR(255) NULL,
  cover_image_url VARCHAR(1000) NULL,
  raw_metadata JSON NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_books_user (user_id),
  KEY idx_books_title (title),
  KEY idx_books_user_title_author (user_id, title, author),
  KEY idx_books_test_data (is_test_data),
  CONSTRAINT fk_books_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS book_candidates (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  query_text VARCHAR(500) NOT NULL,
  candidate_rank INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NULL,
  publisher VARCHAR(255) NULL,
  published_year INT NULL,
  isbn VARCHAR(32) NULL,
  confidence_score DECIMAL(6,5) NULL,
  ai_model VARCHAR(120) NULL,
  prompt_snapshot JSON NULL,
  response_snapshot JSON NULL,
  selected_book_id BIGINT NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_book_candidates_user_query (user_id, query_text),
  KEY idx_book_candidates_selected_book (selected_book_id),
  KEY idx_book_candidates_test_data (is_test_data),
  CONSTRAINT fk_book_candidates_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_book_candidates_selected_book FOREIGN KEY (selected_book_id) REFERENCES books (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reading_sessions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'active',
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  reading_goal VARCHAR(500) NULL,
  start_page INT NULL,
  current_page INT NULL,
  target_page INT NULL,
  progress_note TEXT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  summary TEXT NULL,
  context_snapshot JSON NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_reading_sessions_user (user_id),
  KEY idx_reading_sessions_book (book_id),
  KEY idx_reading_sessions_status (status),
  KEY idx_reading_sessions_pinned (user_id, is_pinned, updated_at),
  KEY idx_reading_sessions_test_data (is_test_data),
  CONSTRAINT fk_reading_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_reading_sessions_book FOREIGN KEY (book_id) REFERENCES books (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS session_windows (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  window_type VARCHAR(40) NOT NULL,
  title VARCHAR(255) NOT NULL,
  position INT NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL DEFAULT 'open',
  context_snapshot JSON NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_session_windows_session_position (session_id, position),
  KEY idx_session_windows_user (user_id),
  KEY idx_session_windows_type (window_type),
  KEY idx_session_windows_test_data (is_test_data),
  CONSTRAINT fk_session_windows_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_session_windows_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS personas (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  description TEXT NULL,
  system_prompt TEXT NOT NULL,
  tone VARCHAR(120) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_personas_name (name),
  KEY idx_personas_active (is_active),
  KEY idx_personas_test_data (is_test_data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  window_id BIGINT NULL,
  user_id BIGINT NOT NULL,
  question_text TEXT NOT NULL,
  question_type VARCHAR(40) NOT NULL DEFAULT 'reflection',
  status VARCHAR(40) NOT NULL DEFAULT 'active',
  ai_model VARCHAR(120) NULL,
  prompt_snapshot JSON NULL,
  context_snapshot JSON NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_questions_session (session_id),
  KEY idx_questions_window (window_id),
  KEY idx_questions_user (user_id),
  KEY idx_questions_type (question_type),
  KEY idx_questions_test_data (is_test_data),
  CONSTRAINT fk_questions_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_questions_window FOREIGN KEY (window_id) REFERENCES session_windows (id),
  CONSTRAINT fk_questions_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS session_highlights (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  page_number INT NULL,
  location_label VARCHAR(120) NULL,
  quote_text TEXT NOT NULL,
  note TEXT NULL,
  highlight_order INT NOT NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_session_highlights_session_order (session_id, highlight_order, id),
  KEY idx_session_highlights_book (book_id),
  KEY idx_session_highlights_user (user_id),
  KEY idx_session_highlights_test_data (is_test_data),
  CONSTRAINT fk_session_highlights_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_session_highlights_book FOREIGN KEY (book_id) REFERENCES books (id),
  CONSTRAINT fk_session_highlights_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS session_tags (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  label VARCHAR(80) NOT NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_session_tags_session (session_id, deleted_at),
  KEY idx_session_tags_user_label (user_id, label),
  KEY idx_session_tags_test_data (is_test_data),
  CONSTRAINT fk_session_tags_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_session_tags_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS session_insights (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  insight_type VARCHAR(60) NOT NULL DEFAULT 'takeaway',
  title VARCHAR(160) NULL,
  content TEXT NOT NULL,
  evidence TEXT NULL,
  insight_order INT NOT NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_session_insights_session_order (session_id, insight_order, id),
  KEY idx_session_insights_user_type (user_id, insight_type),
  KEY idx_session_insights_test_data (is_test_data),
  CONSTRAINT fk_session_insights_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_session_insights_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  window_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  parent_message_id BIGINT NULL,
  role VARCHAR(40) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  content_format VARCHAR(40) NOT NULL DEFAULT 'markdown',
  message_order INT NOT NULL,
  ai_model VARCHAR(120) NULL,
  persona_id BIGINT NULL,
  question_id BIGINT NULL,
  context_snapshot JSON NULL,
  token_usage JSON NULL,
  streaming_status VARCHAR(40) NOT NULL DEFAULT 'complete',
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_messages_session_order (session_id, message_order, id),
  KEY idx_messages_window_order (window_id, message_order, id),
  KEY idx_messages_user (user_id),
  KEY idx_messages_persona (persona_id),
  KEY idx_messages_question (question_id),
  KEY idx_messages_parent (parent_message_id),
  KEY idx_messages_test_data (is_test_data),
  CONSTRAINT fk_messages_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_messages_window FOREIGN KEY (window_id) REFERENCES session_windows (id),
  CONSTRAINT fk_messages_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_messages_persona FOREIGN KEY (persona_id) REFERENCES personas (id),
  CONSTRAINT fk_messages_question FOREIGN KEY (question_id) REFERENCES questions (id),
  CONSTRAINT fk_messages_parent FOREIGN KEY (parent_message_id) REFERENCES messages (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS metrics (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  book_id BIGINT NULL,
  session_id BIGINT NULL,
  window_id BIGINT NULL,
  question_id BIGINT NULL,
  persona_id BIGINT NULL,
  metric_name VARCHAR(120) NOT NULL,
  metric_scope VARCHAR(40) NOT NULL,
  metric_period_start DATE NULL,
  metric_period_end DATE NULL,
  metric_value DECIMAL(18,4) NULL,
  metric_unit VARCHAR(40) NULL,
  metric_details JSON NULL,
  source_ref VARCHAR(255) NULL,
  generated_by VARCHAR(80) NOT NULL DEFAULT 'system',
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_metrics_user_name (user_id, metric_name),
  KEY idx_metrics_session (session_id),
  KEY idx_metrics_window (window_id),
  KEY idx_metrics_question (question_id),
  KEY idx_metrics_persona (persona_id),
  KEY idx_metrics_period (metric_period_start, metric_period_end),
  KEY idx_metrics_test_data (is_test_data),
  CONSTRAINT fk_metrics_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_metrics_book FOREIGN KEY (book_id) REFERENCES books (id),
  CONSTRAINT fk_metrics_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_metrics_window FOREIGN KEY (window_id) REFERENCES session_windows (id),
  CONSTRAINT fk_metrics_question FOREIGN KEY (question_id) REFERENCES questions (id),
  CONSTRAINT fk_metrics_persona FOREIGN KEY (persona_id) REFERENCES personas (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
