CREATE TABLE IF NOT EXISTS session_highlights (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  page_number INT NULL,
  location_label VARCHAR(120) NULL,
  quote_text TEXT NOT NULL,
  note TEXT NULL,
  highlight_order INT NOT NULL,
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_session_highlights_session_order (session_id, highlight_order, id),
  KEY idx_session_highlights_book (book_id),
  KEY idx_session_highlights_user (user_id),
  KEY idx_session_highlights_test_data (is_test_data),
  CONSTRAINT fk_session_highlights_session FOREIGN KEY (session_id) REFERENCES reading_sessions (id),
  CONSTRAINT fk_session_highlights_book FOREIGN KEY (book_id) REFERENCES books (id),
  CONSTRAINT fk_session_highlights_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
