CREATE TABLE IF NOT EXISTS book_knowledge (
  id BIGINT NOT NULL AUTO_INCREMENT,
  isbn VARCHAR(32) NULL,
  title_normalized VARCHAR(255) NOT NULL,
  author_normalized VARCHAR(255) NOT NULL,
  lookup_key_type VARCHAR(40) NOT NULL,
  lookup_key VARCHAR(600) NOT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NULL,
  summary TEXT NULL,
  themes_json JSON NOT NULL,
  discussion_points_json JSON NOT NULL,
  recommended_personas_json JSON NOT NULL,
  famous_quotes_json JSON NOT NULL,
  keywords_json JSON NOT NULL,
  prompt_version VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'ready',
  is_test_data BOOLEAN NOT NULL DEFAULT FALSE,
  failure_reason VARCHAR(500) NULL,
  generated_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_book_knowledge_lookup_version_status (lookup_key_type, lookup_key, prompt_version, status),
  KEY idx_book_knowledge_lookup_isbn_status (isbn, status),
  KEY idx_book_knowledge_lookup_title_author_status (title_normalized, author_normalized, status),
  KEY idx_book_knowledge_status (status),
  KEY idx_book_knowledge_test_data (is_test_data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
