package com.margins.common.error;

import org.springframework.http.HttpStatus;

/**
 * Public, locale-independent API failure identifiers.
 * Each code owns its transport status while frontend i18n owns user-facing copy.
 */
public enum ApiErrorCode {
    COMMON_VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    COMMON_BAD_REQUEST(HttpStatus.BAD_REQUEST),
    COMMON_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    COMMON_FORBIDDEN(HttpStatus.FORBIDDEN),
    COMMON_NOT_FOUND(HttpStatus.NOT_FOUND),
    COMMON_CONFLICT(HttpStatus.CONFLICT),
    COMMON_PRECONDITION_REQUIRED(HttpStatus.PRECONDITION_REQUIRED),
    COMMON_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
    COMMON_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    COMMON_UPSTREAM_ERROR(HttpStatus.BAD_GATEWAY),
    COMMON_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),

    VALIDATION_REQUIRED(HttpStatus.BAD_REQUEST),
    VALIDATION_INVALID(HttpStatus.BAD_REQUEST),
    VALIDATION_INVALID_FORMAT(HttpStatus.BAD_REQUEST),
    VALIDATION_OUT_OF_RANGE(HttpStatus.BAD_REQUEST),
    VALIDATION_SIZE(HttpStatus.BAD_REQUEST),

    AUTH_INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    AUTH_ACCOUNT_LOCKED(HttpStatus.UNAUTHORIZED),
    AUTH_PASSWORD_CONFIRMATION_INVALID(HttpStatus.BAD_REQUEST),
    AUTH_USERNAME_ALREADY_REGISTERED(HttpStatus.CONFLICT),
    AUTH_EMAIL_ALREADY_REGISTERED(HttpStatus.CONFLICT),
    AUTH_REFRESH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    AUTH_ACCOUNT_INACTIVE(HttpStatus.UNAUTHORIZED),
    AUTH_LINKED_USER_NOT_FOUND(HttpStatus.UNAUTHORIZED),
    AUTH_GOOGLE_REGISTRATION_REQUIRED(HttpStatus.PRECONDITION_REQUIRED),
    AUTH_GOOGLE_ACCOUNT_ALREADY_EXISTS(HttpStatus.CONFLICT),
    AUTH_GOOGLE_LINK_REQUIRED(HttpStatus.CONFLICT),
    AUTH_GOOGLE_ALREADY_LINKED(HttpStatus.CONFLICT),
    AUTH_GOOGLE_LINKED_TO_ANOTHER_USER(HttpStatus.CONFLICT),
    AUTH_GOOGLE_LINKING_UNAVAILABLE(HttpStatus.NOT_FOUND),
    AUTH_GOOGLE_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE),
    AUTH_GOOGLE_TOKEN_EXCHANGE_FAILED(HttpStatus.BAD_GATEWAY),
    AUTH_GOOGLE_ID_TOKEN_INVALID(HttpStatus.BAD_REQUEST),
    AUTH_GOOGLE_OAUTH_CANCELLED(HttpStatus.BAD_REQUEST),
    AUTH_GOOGLE_OAUTH_STATE_INVALID(HttpStatus.BAD_REQUEST),
    AUTH_GOOGLE_OAUTH_REQUEST_INVALID(HttpStatus.BAD_REQUEST),
    AUTH_EMAIL_REQUIRED(HttpStatus.BAD_REQUEST),
    AUTH_EMAIL_VERIFICATION_INVALID(HttpStatus.BAD_REQUEST),
    AUTH_BOT_CHALLENGE_INVALID(HttpStatus.BAD_REQUEST),
    AUTH_BOT_CHALLENGE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    AUTH_EMAIL_VERIFICATION_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
    AUTH_VERIFICATION_EMAIL_DELIVERY_FAILED(HttpStatus.BAD_GATEWAY),

    ACCOUNT_PASSWORD_CHANGE_UNAVAILABLE(HttpStatus.BAD_REQUEST),
    ACCOUNT_CURRENT_PASSWORD_INVALID(HttpStatus.UNAUTHORIZED),
    ACCOUNT_PASSWORD_CONFIRMATION_INVALID(HttpStatus.BAD_REQUEST),
    ACCOUNT_RECOVERY_INVALID(HttpStatus.BAD_REQUEST),
    ACCOUNT_INACTIVE(HttpStatus.UNAUTHORIZED),
    ACCOUNT_CHALLENGE_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
    ACCOUNT_CHALLENGE_INVALID(HttpStatus.BAD_REQUEST),

    PRIVACY_CONSENT_INVALID(HttpStatus.BAD_REQUEST),
    PRIVACY_REGISTRATION_INTENT_INVALID(HttpStatus.PRECONDITION_REQUIRED),
    PRIVACY_GOOGLE_REGISTRATION_INVALID(HttpStatus.PRECONDITION_REQUIRED),
    PRIVACY_CONSENT_REQUIRED(HttpStatus.PRECONDITION_REQUIRED),

    CONTACT_INQUIRY_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    CONTACT_INQUIRY_BOT_CHALLENGE_INVALID(HttpStatus.BAD_REQUEST),
    CONTACT_INQUIRY_BOT_CHALLENGE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    CONTACT_INQUIRY_DELIVERY_FAILED(HttpStatus.BAD_GATEWAY),

    MEMBERSHIP_PREMIUM_REQUIRED(HttpStatus.FORBIDDEN),
    BOOK_ALREADY_EXISTS(HttpStatus.CONFLICT),
    SESSION_LAST_WINDOW_REQUIRED(HttpStatus.CONFLICT),
    SESSION_ANSWERED_QUESTION_DELETE_CONFLICT(HttpStatus.CONFLICT),
    SESSION_QUESTION_ANSWER_ROUTE_REQUIRED(HttpStatus.CONFLICT),
    SESSION_QUESTION_ANSWER_TYPE_INVALID(HttpStatus.BAD_REQUEST),
    STREAM_MESSAGE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ApiErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }

    public static ApiErrorCode fromStatus(int status) {
        return switch (status) {
            case 400 -> COMMON_BAD_REQUEST;
            case 401 -> COMMON_UNAUTHORIZED;
            case 403 -> COMMON_FORBIDDEN;
            case 404 -> COMMON_NOT_FOUND;
            case 409 -> COMMON_CONFLICT;
            case 428 -> COMMON_PRECONDITION_REQUIRED;
            case 429 -> COMMON_RATE_LIMITED;
            case 502 -> COMMON_UPSTREAM_ERROR;
            case 503 -> COMMON_SERVICE_UNAVAILABLE;
            default -> status >= 500 ? COMMON_INTERNAL_ERROR : COMMON_BAD_REQUEST;
        };
    }
}
